config/routes.rb
Venuespy::Application.routes.draw do
  
  devise_for :users, {
    :root_path => "cameras#index"
  }

  resources :cameras

  resources :monitors do
    member do
      get 'current'
    end
  end
 
  
  root :to => "cameras#index"
  

end

app/models/camera.rb
class Camera < ActiveRecord::Base
  require "digest/sha1"
  
  belongs_to :user
  
  FTP_UPLOAD_BASE = Venuespy::Application.config.ftp_upload_directory
  
  # These attributes are not saved in the database.
  attr_accessor :password, :password_confirmation
  
  before_validation :create_dirname, :create_libpam_mysql_password
  
  validate :validate_password_confirmation

  before_create :create_directory
  
  validates_presence_of   :ftp_userid
  validates_uniqueness_of :ftp_userid
  validates_format_of     :ftp_userid, :with => /\A[a-zA-Z_][a-zA-Z0-9_\-]*\Z/i
 
  validates_presence_of :ftp_upload_directory
  validates_presence_of :ftp_sha1_password
  
  class NoPictureException < StandardError
  end
  
  def validate_password_confirmation
    # If id == nil then we haven't created it yet and we need a password.
    # Otherwise, we leave it unchanged.
    if (password == nil || password.empty?) && self.id == nil
      self.errors.add(:password, "cannot be empty")
    end
    if password != password_confirmation
      self.errors.add(:password_confirmation, "does not match password")
    end
  end
  
  ##
  # This function returns the most recent file in the
  # ftp upload directory. If there are none, then it
  # raises a NoPictureException.
  #
  def current
    entries = Dir.glob("#{self.ftp_upload_directory}/*.jpg")
    # File.mtime is modified time.
    res = entries.max_by {|f| File.mtime(f)}
    if (res == nil)
      raise NoPictureException.new("No Latest Picture")
    end
    return res
  end
  
  private 
  
  def create_dirname
    if self.ftp_upload_directory == nil || self.ftp_upload_directory.empty?
      self.ftp_upload_directory = "#{FTP_UPLOAD_BASE}/#{ftp_userid}"
    end
  end
  
  def create_directory
    dirname = self.ftp_upload_directory
    if !File.exists? dirname
      Dir.mkdir(dirname)
    end
  end
  
  def create_libpam_mysql_password
    # This is for the following pam_mysql specification: 
    # crypt=4 user=camera usercolumn=ftp_userid passwordcolumn=ftp_sha1_password
    self.ftp_sha1_password = Digest::SHA1.hexdigest(password) if password != nil
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  #  :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  before_save :ensure_authentication_token
  
  def after_token_authentication
    reset_authentication_token!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cameras_controller.rb
class CamerasController < ApplicationController
  before_filter :authenticate_user!, :except => [ :show, :index ]
  
  def current
    @camera = Camera.find_by_ftp_userid[params[:id]]
    send_file @camera.current, :type => 'image/jpeg', :disposition => 'inline'
  end
  
  def index
    @cameras = Camera.all
  end

  def show
    @camera = Camera.find(params[:id])
  end

  def new
    @camera = Camera.new
    @camera.refresh_rate = 2000
  end

  def create
    @camera = Camera.new(params[:camera])
    @camera.user = current_user
    
    if @camera.save
      redirect_to @camera, :notice => "Successfully created camera."
    else
      render :action => 'new' 
    end
  end

  def edit
    @camera = Camera.find(params[:id])
  end

  def update
    @camera = Camera.find(params[:id])
    if @camera.update_attributes(params[:camera])
      redirect_to @camera, :notice  => "Successfully updated camera."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @camera = Camera.find(params[:id])
    @camera.destroy
    redirect_to cameras_url, :notice => "Successfully destroyed camera."
  end
end

app/controllers/monitors_controller.rb
##
# This controller handles the delivery of images from a particular camera.
##
class MonitorsController < ApplicationController
  
  ##
  # Get monitor/:id
  def show
    @camera = Camera.find_by_ftp_userid(params[:id])
    if (@camera == nil)
      render :text => "No such camera", :status => 500
    end
  end
  
  ##
  # GET monitor/current/:id
  # This returns the "current" picture for a particular camera.
  #
  def current
    @camera = Camera.find_by_ftp_userid(params[:id])

    if (@camera != nil)
      set_cache_buster
      logger.info "Sending File #{@camera.current}"
      send_file @camera.current, :type => 'image/jpeg', :disposition => 'inline'
    else
      raise "No Such Camera"
    end
    
    # from @camera.current
    rescue Camera::NoPictureException
      send_default_picture
  end

  private

  ##
  # This function sets the response headers to try to limit picture caching.
  # However, we find that most browsers ignore this, but we try.
  #
  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
  
  def send_default_picture
      #TODO Default Picture
    send_file( Rails.root+"app/assets/images/Test_Pattern.jpg", :type => 'image/jpeg', :disposition => 'inline')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camera_helper.rb
module CameraHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/cameras/_form.html.erb
<%= form_for @camera do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name  %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :ftp_userid, "FTP Userid (must be unique)" %><br />
    <%= f.text_field :ftp_userid, :readonly => @camera.id != nil %>
  </p>
  <p>
    <%= f.label :refresh_rate, "Refresh Rate (miliseconds)" %><br />
    <%= f.text_field :refresh_rate %>
  </p>
  <p>
    <%= f.label :password, "FTP Password" %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "FTP Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/cameras/edit.html.erb
<% title "Edit Camera" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @camera %> |
  <%= link_to "View All", cameras_path %>
</p>

app/views/cameras/index.html.erb
<% title "Cameras" %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Ftp Userid</th>
    <th>Refresh Rate</th>
    <th>Owner</th>
  </tr>
  <% for camera in @cameras %>
    <tr>
      <td><%= camera.name %></td>
      <td><%= camera.description %></td>
      <td><%= camera.ftp_userid %></td>
      <td><%= camera.refresh_rate %> ms</td>
      <td><%= camera.user.email %></td>
      <td><%= link_to "View", monitor_path( :id => camera.ftp_userid ) %></td>
      <td><%= link_to "Info", camera %></td>
      <td><%= link_to "Edit", edit_camera_path(camera) %></td>
      <td><%= link_to "Destroy", camera, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Camera", new_camera_path %></p>

app/views/cameras/new.html.erb
<% title "New Camera" %>

<%= render 'form' %>

<p><%= link_to "Back to List", cameras_path %></p>

app/views/cameras/show.html.erb
<% title "Camera" %>

<p>
  <strong>Owner:</strong><br />
  <%= @camera.user.email %>
</p>
<p>
  <strong>Name:</strong><br />
  <%= @camera.name %>
</p>
<p>
  <strong>Description:</strong><br />
  <%= @camera.description %>
</p>
<p>
  <strong>Ftp Userid:</strong><br />
  <%= @camera.ftp_userid %>
</p>
<p>
  <strong>Ftp Upload Directory:</strong><br />
  <%= @camera.ftp_upload_directory %>
</p>
<p>
  <strong>Ftp Sha1 Password:</strong><br />
  <%= @camera.ftp_sha1_password %>
</p>
<p>
  <strong>Refresh Rate (miliseconds):</strong><br />
  <%= @camera.refresh_rate %>
</p>
<p>
  <strong>
  <%= link_to "View Camera", monitor_path( :id => @camera.ftp_userid ) %>
  </strong>
<p>
  <%= link_to "Edit", edit_camera_path(@camera) %> |
  <%= link_to "Destroy", @camera, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", cameras_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
          <% end %>
      </div>


      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/monitors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "monitors" %>
    <%= javascript_include_tag :application %>
    <%= javascript_include_tag "image_roller" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_nav">
          <% if user_signed_in? %>
            Signed in as <%= current_user.email %>. Not you?
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
          <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/monitors/show.html.erb
<% title "#{@camera.name}" %>

<script type="text/javascript">
/*
 * First argument names the <div> by its id. The second argument
 * names the class of its child <div>. The third argument
 * is the frame refresh rate in milliseconds. The image will be
 * contained in the div in which the class is named.
 * 
 * The imageRoller gets started upon the load of the initial image.
 * The initial image is discarded when started. 
 */
var imageRoller = new ImageRoller("vs_image_roller_box", "vs_image_roller", 
                <%= (@camera.refresh_rate != nil && @camera.refresh_rate > 0) ? @camera.refresh_rate : 2000 %>);
</script>

<div id="vs_image_roller_box">
  <div class="vs_image_roller"
       src='<%= url_for :action => "current", :id => "#{@camera.ftp_userid}" %>'>
     <img 
       src='<%= url_for :action => "current", :id => "#{@camera.ftp_userid}" %>'
       onload='imageRoller.start();'/>
  </div>
</div>
<p><%= link_to "Info", @camera %>|<%= link_to "View All", cameras_path %></p>